substitutions:
  _PROJECT_ID: "906125386407"
  _REGION: "us-central1"
  _SERVICE_NAME: "chatvibes-tts-service"

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/chatvibes-tts-service:$COMMIT_SHA', '.']
# … etc …
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image'
    - 'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:$COMMIT_SHA'
    - '--region'
    - '${_REGION}'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--session-affinity'
    - '--timeout'
    - '3600'
    - '--port'
    - '8080'
    - '--set-env-vars'
    - 'GOOGLE_CLOUD_PROJECT=${_PROJECT_ID}'
    - '--set-secrets'
    - |
      TWITCH_BOT_USERNAME=projects/${_PROJECT_ID}/secrets/twitch-bot-username/versions/latest,
      REPLICATE_API_TOKEN=projects/${_PROJECT_ID}/secrets/replicate-api-token/versions/latest,
      TWITCH_CLIENT_ID=projects/${_PROJECT_ID}/secrets/twitch-client-id/versions/latest,
      TWITCH_CLIENT_SECRET=projects/${_PROJECT_ID}/secrets/twitch-client-secret/versions/latest,
      TWITCH_BOT_REFRESH_TOKEN=projects/${_PROJECT_ID}/secrets/twitch-bot-refresh-token/versions/latest

# Grant Pub/Sub permissions to the Cloud Run service account
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - '-c'
    - |
      # Use the known service account for the chatvibes-tts-service
      SERVICE_ACCOUNT="twitch-sa@chatvibestts.iam.gserviceaccount.com"
      
      echo "Granting Pub/Sub permissions to: $SERVICE_ACCOUNT"
      
      # Grant Pub/Sub Publisher role (to publish TTS events)
      gcloud projects add-iam-policy-binding ${_PROJECT_ID} \
        --member="serviceAccount:$SERVICE_ACCOUNT" \
        --role="roles/pubsub.publisher" \
        --condition=None
      
      # Grant Pub/Sub Subscriber role (to receive TTS events)
      gcloud projects add-iam-policy-binding ${_PROJECT_ID} \
        --member="serviceAccount:$SERVICE_ACCOUNT" \
        --role="roles/pubsub.subscriber" \
        --condition=None
      
      echo "Pub/Sub permissions granted successfully"

images:
- 'gcr.io/${_PROJECT_ID}/chatvibes-tts-service:$COMMIT_SHA'